name: end2end tests

on: [push]

jobs:
  test:

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: ["ubuntu-latest"]
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          pip install pytest
      - name: Install DynaPyt
        run: |
          pip install -e .
      - name: Run the test script
        run: |
          hatch run end2end:run